package generator

const domainTemplate = `// Code generated by repo-code-gen. DO NOT EDIT.

package {{.Options.DomainPackage}}

{{- if .Table.NeedsTime }}
import "time"
{{- end }}

type {{.Table.GoName}} struct {
{{- range .Table.AllColumns }}
	{{.GoName}} {{.GoType}} ` + "`" + `db:"{{.Name}}" json:"{{.JSONTag}}"` + "`" + `
{{- end }}
}
`

const repositoryTemplate = `// Code generated by repo-code-gen. DO NOT EDIT.

package {{.Options.RepositoryPackage}}

import (
	"context"

	"github.com/zeromicro/go-zero/core/stores/sqlx"

	domain "{{domainImport}}"
)

type {{.Table.GoName}}Repository interface {
	Create(ctx context.Context, entity *domain.{{.Table.GoName}}) error
	CreateTx(ctx context.Context, session sqlx.Session, entity *domain.{{.Table.GoName}}) error

	FindBy{{.Table.PK.GoName}}(ctx context.Context, {{.Table.PK.VarName}} {{.Table.PK.GoType}}) (*domain.{{.Table.GoName}}, error)
	FindBy{{.Table.PK.GoName}}Tx(ctx context.Context, session sqlx.Session, {{.Table.PK.VarName}} {{.Table.PK.GoType}}) (*domain.{{.Table.GoName}}, error)
{{- if .Options.GenerateUniqueFinders }}
{{- range .Table.UniqueFinders }}

	{{.Name}}(ctx context.Context, {{.Params}}) (*domain.{{$.Table.GoName}}, error)
	{{.Name}}Tx(ctx context.Context, session sqlx.Session, {{.Params}}) (*domain.{{$.Table.GoName}}, error)
{{- end }}
{{- end }}

	Update(ctx context.Context, entity *domain.{{.Table.GoName}}) error
	UpdateTx(ctx context.Context, session sqlx.Session, entity *domain.{{.Table.GoName}}) error
{{- if .Options.GenerateDelete }}

	Delete(ctx context.Context, {{.Table.PK.VarName}} {{.Table.PK.GoType}}) error
	DeleteTx(ctx context.Context, session sqlx.Session, {{.Table.PK.VarName}} {{.Table.PK.GoType}}) error
{{- end }}
}
`

const mysqlImplTemplate = `// Code generated by repo-code-gen. DO NOT EDIT.

package {{.Options.ImplPackage}}

import (
	"context"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/sqlx"

	domain "{{domainImport}}"
	repository "{{repoImport}}"
)

const {{.Table.VarName}}TableName = "{{.Table.Name}}"

var {{.Table.VarName}}Columns = []string{
{{- range .Table.AllColumns }}
	"{{.Name}}",
{{- end }}
}

type {{.Table.VarName}}Repository struct {
	conn sqlx.SqlConn
}

func {{.Table.ConstructorName}}(conn sqlx.SqlConn) repository.{{.Table.GoName}}Repository {
	return &{{.Table.VarName}}Repository{conn: conn}
}

func (r *{{.Table.VarName}}Repository) Create(ctx context.Context, entity *domain.{{.Table.GoName}}) error {
	return r.create(ctx, r.conn, entity)
}

func (r *{{.Table.VarName}}Repository) CreateTx(ctx context.Context, session sqlx.Session, entity *domain.{{.Table.GoName}}) error {
	return r.create(ctx, session, entity)
}

func (r *{{.Table.VarName}}Repository) create(ctx context.Context, session sqlx.Session, entity *domain.{{.Table.GoName}}) error {
	builder := sq.Insert({{.Table.VarName}}TableName).
		Columns(
{{- range .Table.InsertColumns }}
			"{{.Name}}",
{{- end }}
		).
		Values(
{{- range .Table.InsertColumns }}
			entity.{{.GoName}},
{{- end }}
		)

	query, args, err := builder.ToSql()
	if err != nil {
		return err
	}

	result, err := session.ExecCtx(ctx, query, args...)
	if err != nil {
		return err
	}
{{- if .Table.PK.IsAutoIncr }}

	id, err := result.LastInsertId()
	if err == nil {
		entity.{{.Table.PK.GoName}} = {{if eq .Table.PK.GoType "int64"}}id{{else}}{{.Table.PK.GoType}}(id){{end}}
	}
{{- else }}
	_ = result
{{- end }}

	return nil
}

func (r *{{.Table.VarName}}Repository) FindBy{{.Table.PK.GoName}}(ctx context.Context, {{.Table.PK.VarName}} {{.Table.PK.GoType}}) (*domain.{{.Table.GoName}}, error) {
	return r.findBy{{.Table.PK.GoName}}(ctx, r.conn, {{.Table.PK.VarName}})
}

func (r *{{.Table.VarName}}Repository) FindBy{{.Table.PK.GoName}}Tx(ctx context.Context, session sqlx.Session, {{.Table.PK.VarName}} {{.Table.PK.GoType}}) (*domain.{{.Table.GoName}}, error) {
	return r.findBy{{.Table.PK.GoName}}(ctx, session, {{.Table.PK.VarName}})
}

func (r *{{.Table.VarName}}Repository) findBy{{.Table.PK.GoName}}(ctx context.Context, session sqlx.Session, {{.Table.PK.VarName}} {{.Table.PK.GoType}}) (*domain.{{.Table.GoName}}, error) {
	builder := sq.Select({{.Table.VarName}}Columns...).From({{.Table.VarName}}TableName).
		Where(sq.Eq{"{{.Table.PK.Name}}": {{.Table.PK.VarName}}}).
		Limit(1)

	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp domain.{{.Table.GoName}}
	if err := session.QueryRowCtx(ctx, &resp, query, args...); err != nil {
		return nil, err
	}

	return &resp, nil
}
{{- if .Options.GenerateUniqueFinders }}
{{- range .Table.UniqueFinders }}

func (r *{{$.Table.VarName}}Repository) {{.Name}}(ctx context.Context, {{.Params}}) (*domain.{{$.Table.GoName}}, error) {
	return r.{{.Private}}(ctx, r.conn, {{.Args}})
}

func (r *{{$.Table.VarName}}Repository) {{.Name}}Tx(ctx context.Context, session sqlx.Session, {{.Params}}) (*domain.{{$.Table.GoName}}, error) {
	return r.{{.Private}}(ctx, session, {{.Args}})
}

func (r *{{$.Table.VarName}}Repository) {{.Private}}(ctx context.Context, session sqlx.Session, {{.Params}}) (*domain.{{$.Table.GoName}}, error) {
	builder := sq.Select({{$.Table.VarName}}Columns...).From({{$.Table.VarName}}TableName).
		Where(sq.Eq{ {{.EqMap}} }).
		Limit(1)

	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp domain.{{$.Table.GoName}}
	if err := session.QueryRowCtx(ctx, &resp, query, args...); err != nil {
		return nil, err
	}

	return &resp, nil
}
{{- end }}
{{- end }}

func (r *{{.Table.VarName}}Repository) Update(ctx context.Context, entity *domain.{{.Table.GoName}}) error {
	return r.update(ctx, r.conn, entity)
}

func (r *{{.Table.VarName}}Repository) UpdateTx(ctx context.Context, session sqlx.Session, entity *domain.{{.Table.GoName}}) error {
	return r.update(ctx, session, entity)
}

func (r *{{.Table.VarName}}Repository) update(ctx context.Context, session sqlx.Session, entity *domain.{{.Table.GoName}}) error {
	builder := sq.Update({{.Table.VarName}}TableName)
{{- range .Table.UpdateColumns }}
	builder = builder.Set("{{.Name}}", entity.{{.GoName}})
{{- end }}
	builder = builder.Where(sq.Eq{"{{.Table.PK.Name}}": entity.{{.Table.PK.GoName}}})

	query, args, err := builder.ToSql()
	if err != nil {
		return err
	}

	_, err = session.ExecCtx(ctx, query, args...)
	return err
}
{{- if .Options.GenerateDelete }}

func (r *{{.Table.VarName}}Repository) Delete(ctx context.Context, {{.Table.PK.VarName}} {{.Table.PK.GoType}}) error {
	return r.delete(ctx, r.conn, {{.Table.PK.VarName}})
}

func (r *{{.Table.VarName}}Repository) DeleteTx(ctx context.Context, session sqlx.Session, {{.Table.PK.VarName}} {{.Table.PK.GoType}}) error {
	return r.delete(ctx, session, {{.Table.PK.VarName}})
}

func (r *{{.Table.VarName}}Repository) delete(ctx context.Context, session sqlx.Session, {{.Table.PK.VarName}} {{.Table.PK.GoType}}) error {
	builder := sq.Delete({{.Table.VarName}}TableName).
		Where(sq.Eq{"{{.Table.PK.Name}}": {{.Table.PK.VarName}}})

	query, args, err := builder.ToSql()
	if err != nil {
		return err
	}

	_, err = session.ExecCtx(ctx, query, args...)
	return err
}
{{- end }}
`
